# Benchmark Configuration

paths:
  keypoint_data: "/home/isonaei/ABVFM_benchmark/Benchmark/keypoint_data/ctrl_30fps_superanimal_topviewmouse_snapshot-hrnet_w32-004_snapshot-fasterrcnn_mobilenet_v3_large_fpn-004_27kp.h5"
  video_data: "/home/isonaei/ABVFM_benchmark/data/temp/ctrl_30fps.mp4"
  mask_data: "/home/isonaei/ABVFM_benchmark/castle-ai-feature-support-dinov3-model/projects/2026-01-05-17-00-40-Project_ctrl_30fps.mp4/track/ctrl_30fps.mp4/mask_list.h5"
  dino_embeddings: "/home/isonaei/ABVFM_benchmark/castle-ai-feature-support-dinov3-model/projects/2026-01-05-17-00-40-Project_ctrl_30fps.mp4/latent/dinov3_vitb16/ctrl_30fps_ROI_1_dinov3_vitb16_ctr_rmbg.npz"
  optical_flow_file: "/home/isonaei/ABVFM_benchmark/data/temp/ctrl_30fps_mag.npy"

methods:
  KPMS:
    path: "/home/isonaei/ABVFM_benchmark/Benchmark/lable_data/KPMS_27kp_AR_1e12_Full_1e10_200_0pt5.h5"
    format: "KPMS" 
    enabled: True
  CASTLE:
    path: "/home/isonaei/ABVFM_benchmark/Benchmark/lable_data/CASTLE_lowpass0_25_2_75.csv"
    format: "CASTLE"
    enabled: True
  B-SOiD:
    path: "/home/isonaei/ABVFM_benchmark/Benchmark/lable_data/B-soid_27kp_W3_N100_D0.05.csv"
    format: "BSOID"
    enabled: True

params:
  fps: 30.0
  sigma: 1.0 
  pixel_per_mm: 1.0 
  ssi_window_sec: 0.5


# Visualization
plot:
  colors:
    CASTLE: ["#2E5EAA", "#83C5BE"] 
    BSOID: ["#2A9D8F", "#A7C957"]
    KPMS: ["#E76F51", "#F4A261"]
    
  font_size_title: 20
  font_size_label: 16
  font_size_tick: 14
